- name: transfer downloaded files to shedserver
  hosts: localhost
  become: yes
  tasks:
  - name: check if disk attachede
    stat:
      path: /run/media/anar/
    register: sym
  
  - name: give error if not attached
    debug: 
      msg: "DISK NOT ATTACHED!!! {{sym}}"
    when: sym.stat.exists==False

  - name: copy downloaded
    copy:
      src: /home/anar/Desktop/downloads
      dest: /run/media/anar/New\ Volume/


    