- name: transfer downloaded files to shedserver
  hosts: localhost
  become: yes
  tasks:
  - name: check if disk attachede
    stat:
      path: /run/media/anar/media
    register: sym
  
  - name: give error if not attached
    fail: 
      msg: "DISK NOT ATTACHED!!! "
    when: sym.stat.exists==False

  - name: copy downloaded
    command: cp -r /home/anar/Desktop/downloads/  /run/media/anar/media
       
    


    